from application.main import db
from flask_login import UserMixin


class ChurnDataPrep(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.String(250), nullable=False)
    state = db.Column(db.String(250))
    account_length = db.Column(db.Integer)
    area_code = db.Column(db.String(250))
    international_plan = db.Column(db.String(250))
    voice_mail_plan = db.Column(db.String(250))
    number_vmail_messages = db.Column(db.Integer)
    total_day_minutes = db.Column(db.Float)
    total_day_calls = db.Column(db.Integer)
    total_day_charge = db.Column(db.Float)
    total_eve_minutes = db.Column(db.Float)
    total_eve_calls = db.Column(db.Integer)
    total_eve_charge = db.Column(db.Float)
    total_night_minutes = db.Column(db.Float)
    total_night_calls = db.Column(db.Integer)
    total_night_charge = db.Column(db.Float)
    total_intl_minutes = db.Column(db.Float)
    total_intl_calls = db.Column(db.Integer)
    total_intl_charge = db.Column(db.Float)
    number_customer_service_calls = db.Column(db.Integer)
    cluster = db.Column(db.Integer)
    region = db.Column(db.String(250))
    county = db.Column(db.String(250))
    prediction = db.Column(db.String(250))


class TrainDataPrep(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    date = db.Column(db.String(250), nullable=False)
    state = db.Column(db.String(250))
    area_code = db.Column(db.String(250))
    international_plan = db.Column(db.String(250))
    voice_mail_plan = db.Column(db.String(250))
    number_vmail_messages = db.Column(db.Integer)
    total_intl_calls = db.Column(db.Integer)
    number_customer_service_calls = db.Column(db.Integer)
    account_length = db.Column(db.Integer)
    total_day_minutes = db.Column(db.Float)
    total_day_calls = db.Column(db.Integer)
    total_day_charge = db.Column(db.Float)
    total_eve_minutes = db.Column(db.Float)
    total_eve_calls = db.Column(db.Integer)
    total_eve_charge = db.Column(db.Float)
    total_night_minutes = db.Column(db.Float)
    total_night_calls = db.Column(db.Integer)
    total_night_charge = db.Column(db.Float)
    total_intl_minutes = db.Column(db.Float)
    total_intl_charge = db.Column(db.Float)
    high_day_usage = db.Column(db.Integer)
    high_eve_usage = db.Column(db.Integer)
    high_night_usage = db.Column(db.Integer)
    total_charge = db.Column(db.Float)
    total_calls = db.Column(db.Integer)
    total_minutes = db.Column(db.Float)
    county = db.Column(db.String(250))
    region = db.Column(db.String(250))
    cluster = db.Column(db.Integer)
    churn = db.Column(db.Integer)


class Users(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(250), nullable=False)
    username = db.Column(db.String(250), nullable=False, unique=True)
    email = db.Column(db.String(250), nullable=False, unique=True)
    password = db.Column(db.String(250), nullable=False, unique=True)